### ISSUE TITLE
Graph templates: omit min=0

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2-module-graphite#130]
## Expected Behavior

![goodgraph](https://user-images.githubusercontent.com/6053266/35860507-8f57614c-0b44-11e8-85f7-7fca194fe669.png)

## Current Behavior

![badgraph](https://user-images.githubusercontent.com/6053266/35860484-80a855f2-0b44-11e8-95aa-aa3e5a0a384a.png)

## Context

#71

## Your Environment

Latest bleeding edge stuff only.

**Comment by Al2Klimov** [comment]
@bobapple What's your opinion on this? Possible side effect:

![anothergraph](https://user-images.githubusercontent.com/6053266/35860631-09c43c20-0b45-11e8-8e2c-236d7563c2aa.png)

**Comment by flourish86** [comment]
Seems reasonable to me.

**Comment by bobapple** [comment]
It depends on the data whether if setting the minimum to `0` is a good idea or not. Sometimes you want to see even small changes you wouldn't see if the minimum is `0`. On the other hand, if you omit the `min=0`, there are scenarios where you would see a "huge" increase even if it's not that big, because you're looking just at the upper end of the range.

I would decide based on the check plugin if setting `min=0` is a good idea or not.
