### ISSUE TITLE
Add link to graph to jump to Graphite / Grafana

### ISSUE THREAD

**Issue by LordHepipud** [Icinga/icingaweb2-module-graphite#155]
Right now graphs are only displayed, without the possibilty to easily navigate to Graphite or Grafana.
It would be nice to have such an option, to be able to view the Graph within Graphite or Grafana, allowing a closer look to it.

## Expected Behavior

Rendered images should contain a link to Graphite / Grafana

## Current Behavior

Only the images are rendered and displayed, without the possibility to access the graph in an easy way.

## Possible Solution

Add a dynamic link to Graphite / Grafana to the image

## Your Environment

* Module version (System - About): 1.0.0
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.2
* Operating System and version: Debian Jessie
* Webserver, PHP versions:

**Comment by dnsmichi** [comment]
Since we hide the URL and route ourselves, this should be made a permission for advanced users.

**Comment by Al2Klimov** [comment]
@dnsmichi IMO we "hide" the URL "by accident" and not for security reasons. (If a Graphite Web instance is secured only by hiding its URL...)
@bobapple What's your opinion on this (from the UX POV)?

**Comment by bobapple** [comment]
First of all, we can only link to Graphite and not Grafana.

If we would link to Graphite we need to consider the following things:
- We only have links to the renderer API (eg. `https://example.com/metrics/expand?query=icinga2.icinga_com.host.hostalive.perfdata.%2A.value`). These links are not sufficient, they won't let you do anything with the graph if you don't know exactly the renderer API parameters.
- Therefore, we would need to link to the Graphite Web Composer (replace `/renderer` in the URL with `/composer`
- The user may not have access to the Graphite Web interface, since requests are running from the Icinga Web 2 machine to the Graphite server.

Conclusion: 
I wouldn't implement this feature unless it's needed by more then more person (sorry @LordHepipud :-))
If we implement it, it has to be opt-in only, because of the possible access restriction that users may experience. The image should be linked without any extra button or link.

**Comment by seidler2547** [comment]
It's definitely something we sorely miss after switching from Munin to Icinga. So +1 from me.
