### ISSUE TITLE
improvement: make graphs easier to compare and more responsible

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2-module-graphite#172]
## Expected Behavior
it should be easy to compare graphs.  

## Current Behavior
1. Setting filters using this URL: icingaweb2/graphite/list/services is hard because of a refresh or enter pressed i dont know.
2. The graphics are not easy to compare, because they are not among each other, but also next to each other.
3. Graph is rendered by Graphite not by the module itself. 

## Possible Solution
Just fetch the values of the graphs from graphite. Use a modern js library to render the graphs.

Allow the user to set markers in a graph. I set a marker on a peak, click on another service in icingaweb and see if the peak is at the same time.

**Comment by Al2Klimov** [comment]
@bobapple What's you opinion on this?

**Comment by bobapple** [comment]
Generally I agree with @cstegm. We decided to use the Graphite-Web renderer because it is usually faster then rendering in the browser. Being fast is one of the most important requirements of (official) Icinga Web 2 modules. Though, graphs look nicer when using a proper JS library and an interaction with the graph would be possible. We may consider a change from the Graphite-Web renderer to a JS library in the future. For the midterm however, we will stay with the current solution. The template engine would be affected as well btw.

@cstegm thank you for your feedback, it's much appreciated.

**Comment by Al2Klimov** [comment]
And: JS is single-threaded after all...

**Comment by cstegm** [comment]
@Al2Klimov what about using html5 web-workers to speed things up? https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by Al2Klimov** [comment]
Please ask @bobapple, not me. He's head of design decisions.

**Comment by Al2Klimov** [comment]
... and architecture.

**Comment by Al2Klimov** [comment]
... and everything else.

**Comment by nilmerg** [comment]
I think we can all agree that this can be closed. No change for, soon, 6 years. And no plans to change this either.
