### ISSUE TITLE
No image frome module

### ISSUE THREAD

**Issue by Zyablokrak** [Icinga/icingaweb2-module-graphite#177]
Hi
After installing module , i haven't see some graphs , even blank : 

  
![image](https://user-images.githubusercontent.com/41532452/43042591-236d43b0-8d8b-11e8-9e1c-121d54ed8b50.png)
* in host selection nothing.
*performance data on and update
*use locale url  http:\\localhost\render\?

* Module version (System - About):  1.0.1
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`):  r2.8.4-1
* Graphite (carbon, web, whisper) version: carbon - 2.0.16 whisper 0.9.16
* Operating System and version: Centos 7
* Webserver, PHP versions: apache 2.4.6 Python 2.7.5

**Comment by Al2Klimov** [comment]
Hello @Zyablokrak and thank you for reporting!

This is likely to be a rendering error: Your browser requests the actual graph(s), but Icinga Web 2 returns an error instead of a valid image and the browser just swallows it.

Please upgrade the Graphite module to v1.1.0 and check whether that fixes it. If not, please consult your browser's developer console for the URLs being requested and share them with the responses.

Best,
AK

**Comment by Zyablokrak** [comment]
Ok , now, after update it's work , thanks
