### ISSUE TITLE
Replace underscore in graph titles

### ISSUE THREAD

**Issue by Baboon92** [Icinga/icingaweb2-module-graphite#191]
## Expected Behavior
Graph titles can show the original character which has to be replaced for graphite backend, e.g. "Disk /" instead of "Disk _".

## Current Behavior
Graph titles can use strings or/and variables like "Disk $disk$" which results in "Disk _" instead of "Disk /".

## Possible Solution
Provide a function like replace in the configuration, so you can write something like `title = "Disk replace($disk$, _, /)`.

## Context
I am trying to get the graphs as beautiful and meaningful as possible.

## Your Environment
* Module version (System - About): 1.1.0
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): 2.10.1
* Graphite (carbon, web, whisper) version: 1.1.2
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache Httpd + PHP FPM 7.1

**Comment by bobapple** [comment]
I wouldn't consider it a bug. This way Icinga makes sure that you don't push any special characters to Graphite that cannot be handled later. I wouldn't like to add custom functions to our template engine. I would keep it clean by allowing only Graphite functions. Maybe this could be achieved with some existing Graphite function.

**Comment by Al2Klimov** [comment]
Of course Icinga 2 has not to write some characters to Graphite, but instead of replacing all of them with one particular (making the translation one-way) Icinga 2 could do some kind of URL-encoding instead – couldn't it?

**Comment by dnsmichi** [comment]
Escaping characters which cannot be handled by Graphite is implemented since 2.2.0 (icinga/icinga2#2031). We've also changed the schema in 2.4.0 with icinga/icinga2#3090 already. Changing the escaping would require a new schema version again. Imho not worth the time and migration effort.

Graphite 1.1 adds support for custom functions exposed in the render api.
https://grafana.com/blog/2018/01/11/graphite-1.1-teaching-an-old-dog-new-tricks/

Writing such and loading into Graphite sounds easy (don't have a Graphite here to try it out). And once that's documented for the templates here with a short example, this will likely help everyone else.
https://graphite.readthedocs.io/en/1.1.1/functions.html#function-plugins

**Comment by Al2Klimov** [comment]
I'm sorry @Baboon92, but IMO unescaping by guessing would be a workaround which is not to be preferred if the root cause – Icinga 2's schema – *may* be fixed. Feel free to open an Icinga 2 issue for this.

**Comment by Al2Klimov** [comment]
PS: #178 prooves that you should not guess the original character, but make it reconstructible.

**Comment by dnsmichi** [comment]
I've written a short howto for creating such custom functions. Pretty nifty API, it has.

https://community.icinga.com/t/graphite-render-api-add-custom-functions-for-better-metric-formatting/218
