### ISSUE TITLE
Module description and version in Icinga Web 2

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Icinga/icingaweb2-module-graphite#22]
Hello. 
Please add the **version number** of the module and the **module description** for Icinga Web 2

![no module info](https://cloud.githubusercontent.com/assets/17614847/24602910/d9d5897e-186f-11e7-8336-90a2b0c4214d.png)

**Comment by lazyfrosch** [comment]
Hey, there hasn't been a tagged version of the module.

https://github.com/Icinga/icingaweb2-module-graphite/releases

Therefor no version can be used there.

**Comment by Thomas-Gelf** [comment]
It would be great if we could finally release this one, as it provides nice features since quite some time. However, it never got the required priority and no one is currently actively working on it. To get ready for a release, this module basically waits for the following features:
* Zoom and/or time-range selection. Not complicated at all. At the time being this has been postponed as there where planes for a central time-range-selection-component in Icinga Web 2 - which still does not exist. We could easily develop something very simple, dedicated for this module - this shouldn't be a blocker at all
* Ship more default templates. Once you understood them, it's very easy to create them - we just need someone willing to so so. Or someone sponsoring someone allowing him to "force" someone else to do so.
* Documentation: installation is easy and already mostly covered. Template handling and creation needs a dedicated chapter with lot's of details, as that's what makes this module differ

Cheers,
Thomas

**Comment by Aleksey-Maksimov** [comment]
Thanks for the reply, Thomas. We will wait for release :)
