### ISSUE TITLE
Url Encode fails on [] range chars

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icingaweb2-module-graphite#220]
I try to use the range filter method from graphite but the encoding fails horribly!

`suite.value = "$service_name_template$.perfdata.suite_[a-z]*.value"`

Results in this: 

`'http://localhost:8000/metrics/expand?query=icinga2.hostname.services.servicename.passive.perfdata.suite_%5B%5B%5Da-z%5B%5D%5D%2A.value'`

## Your Environment

* Module version (System - About): 1.1.0
* Icinga Web 2 version and modules (System - About): 2.7.1
* Icinga 2 version (`icinga2 --version`): 2.10.5_1
* Graphite (carbon, web, whisper) version: 1.1.5 
* Operating System and version: Ubuntu 16.04 LTS 
* Webserver, PHP versions: 7.2.19-0ubuntu0.18.04.2 apache2

**Comment by sukhwinder33445** [comment]
Notes:

I tried to reproduce this and found out that the template is ignored and the default template is used as fallback if metricpath contains `[]`.



I changed the `users.ini` template as following: 
```
[users.metrics_filters]
users = "$service_name_template$.perfdata.u[sd]ers.value"
```

`Template.php: 92 $query->fetchColumn()` -> `MetricsQuery::fetchColumn(): 145` GraphiteWebClient::escapeMetricPath() changes `.u[sd]ers.value` to `.u[[]sd[]].value` and set the query param. 
This change leads to an empty `$res->result`. Without this change, `$res->result` has a result.

But now in line `Template.php: 100 $curve[0]->reverseResolve($metric)` returns false. Because it can't match the $metric given as parameter with pattern (because the pattern still looks for [] in the given $resolved string). $resolved is the string we get from GraphiteWebClient as result, and it doesn't contain []. Now the `$vars = false` and `$metrics[]` is still empty. Template is skipped, default template is used in the loop.
