### ISSUE TITLE
Is this repository still alive?

### ISSUE THREAD

**Issue by m4k5ym** [Icinga/icingaweb2-module-graphite#252]
Last release was literally 3 years ago.

Any further plans? Fixing issues at least? If not mark it as it is. dead.

Then I can stop waiting for bugfixes and improvements.

**Comment by nilmerg** [comment]
Are there any breaking/pressing issues I'm not aware of? Please tell me which issues you're talking of.

And regarding plans/improvements. There's the [v1.2.0](https://github.com/Icinga/icingaweb2-module-graphite/milestone/5) milestone, though that's also open since over a year. I understand that this isn't a positive sign of activity, but we currently don't have the time to fully invest in this project. Though, it's still an opensource project. If you can provide help, it's highly appreciated.

**Comment by m4k5ym** [comment]
Yes I already discussed it with Mr Klimov that exporting into PDF is not working and there has been no further answer until today. This feature is somehow mandatory for creating useful customer / manager reports.

**Comment by henningw** [comment]
@nilmerg It would be great to release at least an updated version, e.g. 1.2.0. You can easily waste hours on something that is already fixed, if you choose the latest available release tag as base.

**Comment by m4k5ym** [comment]
No further responses.

ClOsEd
