### ISSUE TITLE
Beautify existing graphs

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2-module-graphite#60]
Update existing templates to make sure the corresponding graphs look prettier and more "modern". We will consult with @flourish86 to find out which colors, sizes etc. to use.

**Comment by Al2Klimov** [comment]
CC @flourish86

**Comment by Al2Klimov** [comment]
As discussed w/ @flourish86:

If you select a long time range to show data for, then you have a lot of labels on the X-axis.
After a lot of investigation and testing I've made the labels themselves a bit better, but the problem is the amount of major grid lines (and their labels). Even `"summarize($metric, '1year', 'avg', true)"` seems not to help, so I need help from master @bobapple...

**Comment by Al2Klimov** [comment]
Note for the future myself:

As discussed w/ @flourish86:

Show max 2 graphs in the detail view (spoiler, subcontainer?).

**Comment by nilmerg** [comment]
Rebased with master.
